### PR TITLE
Fix destructure structs implementation

### LINKED ISSUE #2: Destructure Structures
```
defmodule Foo do
  defstruct bar: 0

  import Destructure

  def take_foo(d%Foo{bar}) do
    :ok
  end
end
```

This fails to compile. I would like it to compile, and have `bar` in scope in `take_foo/1`.

### PR DESCRIPTION
**Pull request by chouzan**
Resolves #2

### CODE REVIEW

**Comment by chouzan** [comment]
@danielberkompas please have a look

File: test/destructure_test.exs [hunk 1]
```diff
@@ -7,7 +7,23 @@ defmodule DestructureTest do
...
+    defstruct [:people]
+  end
+
   alias __MODULE__.Person
 
   doctest Destructure
+
+  describe "structs" do
+    test "can't match with different structs" do
+      refute d(%People{}) == %Person{}
```
Comment (danielberkompas) [inline test/destructure_test.exs]: Shouldn't this be `refute d(%People{}) = %Person{}`?

Comment (chouzan) [reply test/destructure_test.exs]: No, if we use assignment match, it will raise `MatchError` before `refute` evaluation takes action. Try using `assert d(%People{}) == %Person{}`, we will get the expected failure
```elixir
1) test structs can't match with different structs (DestructureTest)
     test/destructure_test.exs:17
     Assertion with == failed
     code: d(%People{}) == %Person{}
     lhs:  %DestructureTest.People{people: nil}
     rhs:  %DestructureTest.Person{email: nil, name: nil}
     stacktrace:
       test/destructure_test.exs:18: (test)
```

Comment (chouzan) [reply test/destructure_test.exs]: Or should I change it to use `assert_raise`? I guess it's more make sense to do it

**Comment by chouzan** [comment]
@danielberkompas please have a look with the update

**Comment by danielberkompas** [comment]
Looks good to me, @muhifauzan!
